### ISSUE TITLE
Server crash just now.

### ISSUE THREAD

**Issue by apollodeathstar** [Liveandletdie/becti_zerty_OFPS_Extended.Altis#13]
server crash late game, no msg received from server. server restarted fine.

**Comment by Liveandletdie** [comment]
Pretty sure crash is related to the B2 bomber, did you happen to notice if anyone spawned one?

**Comment by apollodeathstar** [comment]
could not say.

**Comment by Liveandletdie** [comment]
100% without a doubt the B2 bomber.....the B1 is ok and does not crash server. We need to either reskin the b1 for both sides or find an alternative.
