### ISSUE TITLE
People are attaching C4 to Teran UAV's

### ISSUE THREAD

**Issue by apollodeathstar** [Liveandletdie/becti_zerty_OFPS_Extended.Altis#18]
People are attaching stacks of C4 to UAV's and sending them at players/ vehs. Before this would be unprofitable now with the PVP changes this becomes decently viable, esp if that player is in a veh or capping a flag. I mean its funny of course but yeah a little ridiculous

**Comment by johnsmm** [comment]
must be fun

**Comment by Liveandletdie** [comment]
lol agreed....players have been able to do this for some time now....uav backbacks are 3k, not a bad investment lol
