### ISSUE TITLE
Fixed C17 damage and norrkopin maxspeed need uploaded to server

### ISSUE THREAD

**Issue by apollodeathstar** [Liveandletdie/becti_zerty_OFPS_Extended.Altis#28]
I fixed the C17 damage to be in line with other aircraft, tested it and it works fine. C-17 can no longer take copious amounts of tank rounds, now it goes down in 2 hits of AT tank rounds or 1 HE round. Apparently the creator of the USAF pack is supposed to come out with a update soon(TM)

The norrkopin was unable to achieve its real world max speed of 75kph so I changed its water resistance coefficient so it could hit its max speed.

This is the C17 Config
[config.zip](https://github.com/Liveandletdie/becti_zerty_OFPS_Extended.Altis/files/198169/config.zip)

This is the norrkopin Config.
[config.zip](https://github.com/Liveandletdie/becti_zerty_OFPS_Extended.Altis/files/198188/config.zip)

Extract, add to their respective addon PBO locations. update the respective mod pack for steam

Also what is the preferred way to submit changes to the PBO's via github? this seemed like the only solution I could find.

@SpanishSurfer @Liveandletdie @johnsmm

**Comment by Liveandletdie** [comment]
I assume these configs are from the mod pack versions? 

Yea i think this works fine for submitting mod edits, either this or just hit me up on steam! Did we ever give you the link to the spreadsheet?

**Comment by apollodeathstar** [comment]
Yep they are the configs for the mod pack versions from the OFPS steam workshop used currently on the live server.

Nah I dont have a link to the spreadsheet.

**Comment by Liveandletdie** [comment]
Ill get these added on the next mod pack update
