### ISSUE TITLE
Reward for HC AI Kills not working

### ISSUE THREAD

**Issue by johnsmm** [Liveandletdie/becti_zerty_OFPS_Extended.Altis#6]
Reward for killing AI that been transferred to HC doesn't work.
We need to get this fixed

**Comment by johnsmm** [comment]
Not sure if this helps, this is from another CTI mission that used their own HC

Recive_EvenHandler.sqf
`if (isMultiplayer) then{       "Packet_EventHandler" addPublicVariableEventHandler {       private["_EventHandlerName", "_EventHandlerData"];      _EventHandlerName   = _this select 1 select 0;                      _EventHandlerData   = _this select 1 select 1;                                              switch _EventHandlerName do {           case ("Kill")       : {                                             disableSerialization;               private["_DeadBody", "_Price", "_DeadBodyEnemy", "_DeadBodyName", "_Text", "_KillerIsPlayer"];              _DeadBody       = _EventHandlerData select 0;                           _Price          = _EventHandlerData select 1;                           _DeadBodyEnemy  = _EventHandlerData select 2;                           _KillerIsPlayer = _EventHandlerData select 3;                           _DeadBodyName   = getText (configFile >> "CfgVehicles" >> (typeOf _DeadBody) >> "displayName");             _Text           = if (_DeadBodyEnemy) then {"KILL"} else {"TEAM KILL"};                                                     [Player, 0, _Price] call SetPlayerSupplyMoney;                                              if (_KillerIsPlayer) then   {_Price spawn HintMSG_KillPay};                     ["", _DeadBodyName, _Price] spawn HintMSG_Pay;                                                                              };      };  };};`

EH_Killed_Unit.sqf
`#include "EH_Functions.sqf"private ["_DeadBody","_Killer","_DeadBodyName","_Group","_Units", "_PlayersWhoKill", "_DeadBodyPrice",       "_DeadBodyEnemy"];_DeadBody        = _this select 0;                           _Killer         = _this select 1;                           _DeadBodySide   = _DeadBody call _GetDeadBodySide;          _DeadBodyName   = getText (configFile >> "CfgVehicles" >> (typeof _DeadBody) >> "displayName");_PlayersWhoKill  = _Killer call _KillerManOrVehicleCrew;     _DeadBodyPrice  = _DeadBody call _UnitPriceFromData;        _DeadBodyEnemy  = if (side _Killer != _DeadBodySide) then {true} else {false};if (_Killer != _DeadBody) then{   if (count _PlayersWhoKill > 0) then {       {           private["_Price", "_Text", "_KisP", "_Text2"];          _KisP   = [_Killer, _x] call _KillerIsPlayer;                               _Price  = (_DeadBodyPrice select 1) / (count _PlayersWhoKill);          _Price  = if (isPlayer _DeadBody) then {500} else {_Price};                 _Price  = if (_DeadBodyEnemy) then {_Price} else {-_Price};                 _Text   = if (_DeadBodyEnemy) then {"KILL"} else {"TEAM KILL"};             _Text2  = if (_KisP) then {"YOU"} else {""};                                            if (!isNull _x) then            {                                                   ["Kill", _x, [_DeadBody, _Price, _DeadBodyEnemy, _KisP]] call Send_EventHandler;            };      } forEach _PlayersWhoKill;  };};_DeadBody spawn _DeleteDeadBody;`

**Comment by SpanishSurfer** [comment]
We fixed this right? However, sometimes rewards are $5000 for a rifleman kill???
