### ISSUE TITLE
Crazy UAV waypoint....all moving to SW corner

### ISSUE THREAD

**Issue by Liveandletdie** [Liveandletdie/becti_zerty_OFPS_Extended.Altis#7]
title says it all

**Comment by apollodeathstar** [comment]
Yeah I have had issues with the UAV's as well tring to move to the SW both on this ver and the previous one.

**Comment by SpanishSurfer** [comment]
With HC turned off, the uavs behave normally

**Comment by johnsmm** [comment]
need to add UAV class or group to HC ignore.

**Comment by johnsmm** [comment]
Fixed this but, waypoint still creates. "users can delete and create their own"
HC ignores UAVs now, not sure whats going on with waypoint.
